# Generated by Django 3.1.2 on 2021-09-22 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganesh', '0003_auto_20210922_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
