# Generated by Django 3.1.2 on 2021-11-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganesh', '0005_auto_20211109_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
