# Generated by Django 3.1.2 on 2021-12-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganesh', '0008_auto_20211225_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
