# Generated by Django 4.2.13 on 2024-06-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganesh', '0010_auto_20220207_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='certification/')),
                ('link', models.URLField()),
            ],
        ),
    ]
