# Generated by Django 5.2.8 on 2026-05-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganesh', '0011_certification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certification',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='certification',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
