# Generated by Django 5.2.8 on 2026-05-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganesh', '0012_alter_certification_options_certification_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certification',
            options={'ordering': ['sort_order']},
        ),
        migrations.RemoveField(
            model_name='certification',
            name='order',
        ),
        migrations.AddField(
            model_name='certification',
            name='sort_order',
            field=models.IntegerField(blank=True, db_index=True, default=0),
            preserve_default=False,
        ),
    ]
